add config and version parameters to proton-tkg-build

diff --git a/scripts/proton-tkg-build b/scripts/proton-tkg-build
--- a/scripts/proton-tkg-build
+++ b/scripts/proton-tkg-build
@@ -1,11 +1,18 @@
 #!/bin/bash
 set -e
 fetch-wine-tkg
+config_filename=${1:-"proton-tkg-std.cfg"}
+version=$2
+configs_dir="/usr/share/wine-docker-builder/configs"
 cd wine-tkg-git/proton-tkg
+cfgfile=`find "$configs_dir" -maxdepth 1 -name "$config_filename" -print -quit`
+[[ -z "$cfgfile" ]] && (echo "can't find config file: $config_filename" 1>&2; exit -1)
+echo "$cfgfile"
 mkdir -p ~/.config/frogminer
-cp /usr/share/wine-docker-builder/configs/proton-tkg-std.cfg ~/.config/frogminer/proton-tkg.cfg
+cp "$cfgfile" ~/.config/frogminer/proton-tkg.cfg
 sed -i 's/read -rp "Your S.*/_no_steampath=y/' proton-tkg.sh
 sed -i '\+git clone https://github.com/Frogging-Family/community-patches.git$+ s+$+ \&\& cp /usr/share/wine-docker-builder/patches/* community-patches/wine-tkg-git/+' ../wine-tkg-git/wine-tkg-scripts/prepare.sh
+[[ -z "$version" ]] || echo -e "\n_staging_version=$version" >> ~/.config/frogminer/proton-tkg.cfg
 ./proton-tkg.sh
 rm ~/.config/frogminer/proton-tkg.cfg
 protonname=`ls -t1 |  head -n 1`
